from ChemConstants import C_BACT_INIT, C_GLUC_INIT, C_LA_INIT, C_TWEEN_INIT, FERMENT_WATER_VOL, CHEMICALS
from GrowthCurve import C_GLUC_FINAL, C_BACT_FINAL, C_LA_FINAL
from Conversions import g_to_kg, kg_to_g
from SaltCalcs import C_SALT_OUT
import FluidStream as FS

# INPUTS

VOL_CSL_IN = .12 * FERMENT_WATER_VOL
MASS_CSL_IN = VOL_CSL_IN / CHEMICALS['Corn Steep Liquor'][1]
C_CSL_IN = kg_to_g(MASS_CSL_IN) / FERMENT_WATER_VOL

C_GLUC_IN = C_GLUC_INIT
MASS_GLUC_IN = g_to_kg(C_GLUC_IN * FERMENT_WATER_VOL)
VOL_GLUC_IN = MASS_GLUC_IN / CHEMICALS['Glucose'][1]

C_CaLA_IN = C_SALT_OUT
MASS_CaLA_IN = g_to_kg(C_CaLA_IN * FERMENT_WATER_VOL)
VOL_CaLA_IN = MASS_CaLA_IN / CHEMICALS['Calcium Lactate'][1]

C_CaCO4_IN = 0.0
MASS_CaCO4_IN = 0.0
VOL_CaCO4_IN = 0.0

C_TWEEN_IN = C_TWEEN_INIT
MASS_TWEEN_IN = g_to_kg(C_TWEEN_IN * FERMENT_WATER_VOL)
VOL_TWEEN_IN = MASS_TWEEN_IN / CHEMICALS['Tween 80'][1]

C_BACT_IN = C_BACT_INIT
MASS_BACT_IN = g_to_kg(C_BACT_IN * FERMENT_WATER_VOL)
VOL_BACT_IN = MASS_BACT_IN / CHEMICALS['Bacteria'][1]

C_LA_IN = C_LA_INIT
MASS_LA_IN = g_to_kg(C_LA_IN * FERMENT_WATER_VOL)
VOL_LA_IN = MASS_LA_IN / CHEMICALS['Lactic Acid'][1]

SOLUBLES_SUM = VOL_CSL_IN + VOL_GLUC_IN + VOL_CaLA_IN + VOL_TWEEN_IN + VOL_BACT_IN + VOL_LA_IN + VOL_CaCO4_IN

VOL_WATER_IN = FERMENT_WATER_VOL - SOLUBLES_SUM
MASS_WATER_IN = VOL_WATER_IN * CHEMICALS['Water'][1]
C_WATER_IN = kg_to_g(MASS_WATER_IN) / FERMENT_WATER_VOL

TOTAL_VOL_IN = VOL_CSL_IN + VOL_GLUC_IN + VOL_CaLA_IN + VOL_TWEEN_IN + VOL_BACT_IN + VOL_LA_IN + VOL_CaCO4_IN + VOL_WATER_IN
TOTAL_MASS_IN = MASS_CSL_IN + MASS_GLUC_IN + MASS_CaLA_IN + MASS_TWEEN_IN + MASS_BACT_IN + MASS_LA_IN + MASS_CaCO4_IN + MASS_WATER_IN

print "Volume in = ", TOTAL_VOL_IN
print "Mass in = ", TOTAL_MASS_IN

# OUTPUTS

MASS_CSL_OUT = MASS_CSL_IN
VOL_CSL_OUT = VOL_CSL_IN

C_GLUC_OUT = C_GLUC_FINAL
MASS_GLUC_OUT = g_to_kg(C_GLUC_OUT * FERMENT_WATER_VOL)
VOL_GLUC_OUT = MASS_GLUC_OUT / CHEMICALS['Glucose'][1]

MASS_CaLA_OUT = MASS_CaLA_IN
VOL_CaLA_OUT = VOL_CaLA_IN

C_CaCO4_OUT = 0.0
MASS_CaCO4_OUT = 0.0
VOL_CaCO4_OUT = 0.0

MASS_TWEEN_OUT = MASS_TWEEN_IN
VOL_TWEEN_OUT = VOL_TWEEN_IN

C_BACT_OUT = C_BACT_FINAL
MASS_BACT_OUT = g_to_kg(C_BACT_OUT * FERMENT_WATER_VOL)
VOL_BACT_OUT = MASS_BACT_OUT / CHEMICALS['Bacteria'][1]

C_LA_OUT = C_LA_FINAL
MASS_LA_OUT = g_to_kg(C_LA_OUT * FERMENT_WATER_VOL)
VOL_LA_OUT = MASS_LA_OUT / CHEMICALS['Lactic Acid'][1]

MASS_WATER_OUT = MASS_WATER_IN
VOL_WATER_OUT = VOL_WATER_IN

TOTAL_VOL_OUT = VOL_CSL_OUT + VOL_GLUC_OUT + VOL_CaLA_OUT + VOL_CaCO4_OUT + \
                VOL_TWEEN_OUT + VOL_BACT_OUT + VOL_LA_OUT + VOL_WATER_OUT
TOTAL_MASS_OUT = MASS_CSL_OUT + MASS_GLUC_OUT + MASS_CaLA_OUT + MASS_CaCO4_OUT + \
                 MASS_TWEEN_OUT + MASS_BACT_OUT + MASS_LA_OUT + MASS_WATER_OUT

output_stream = FS.FluidStream(MASS_WATER_OUT, MASS_LA_OUT, MASS_CaLA_OUT, MASS_GLUC_OUT,
                               MASS_BACT_OUT, MASS_CSL_OUT, MASS_TWEEN_OUT, 0, 47)

print "Volume out = ", TOTAL_VOL_OUT
print "Mass out = ", TOTAL_MASS_OUT

